---

#- import_playbook: build-base.yml

- name: Set up CephFS backup
  hosts: backup
  roles:
    - backup.pbsclient
    - backup.cephfs
    - role: backup.service
      serviceName: cephfs
      serviceDescription: Back up CephFS filesystems
      servicePath: /opt/backup/cephfs-backup.sh
