---

- name: Builds a VM from a fresh Debian install
  hosts: all

  roles:
    - debian.base
    - debian.notime
    - debian.sudoers
    - { role: "debian.rsyslog", rsyslog_host: "192.168.2.4" }
    - debs.setup
    - vim.setup
    - debian.kerberos
