---

- name: Builds a DigitalOcean machine from a fresh Debian install
  hosts: all

  roles:
    - gai.private
    - debian.base
    - role: debian.ntpsec
      hosts: ["time.nist.gov"]
    - debian.sudoers
    - debian.rsyslog
    - vim.setup
    - debian.kerberos
