---

- name: Build a mail exchanger
  hosts: do
  roles:
    - mail.postfix
    - mail.opendkim
    - mail.opendmarc
    - mail.clamav
    - mail.spamd
    - mail.spamass-milter
    - mail.milter-checkrcpt
