- name: Builds a machine from a fresh Debian install
  hosts: all

  roles:
    - apt-cache.proxy
    - gai.private
    - debian.base
    - role: debian.notime
      when: is_ct is defined and is_ct
    - role: debian.ptp_time
      when: is_ct is undefined or not is_ct
    - debian.sudoers
    - debian.rsyslog
    - role: debian.ssmtp
      when: is_do is undefined or not is_do
    - vim.setup
    - ssh.setup
    - role: debian.kerberos
      when: skip_kerberos is undefined or not skip_kerberos
