---

#- import_playbook: build-vm.yml

- name: Set up NFS mounts
  hosts: all
  roles:
    - servarr.nfs

- name: Set up Sonarr
  hosts: sonarr
  roles:
    - role: "servarr.managerr"
      service: "sonarr"
      servicePort: "8989"
      version: "4.0.8.1874"
      branch: main
      arch: x64

- name: Set up Radarr
  hosts: radarr
  roles:
    - role: "servarr.managerr"
      service: "radarr"
      servicePort: "7878"
      branch: master
      version: "5.8.3.8933"

- name: Set up Prowlarr
  hosts: prowlarr
  roles:
    - role: servarr.managerr
      service: prowlarr
      servicePort: "9696"
      branch: master
      version: "1.21.2.4649"

- name: Set up qBittorrent
  hosts: qbittorrent
  roles:
    - servarr.qbittorrent
