- name: Builds a machine from a fresh Debian install
  hosts: all

  roles:
    - apt-cache.proxy
    - debian.base
    - role: debian.notime
      when: is_ct
    - role: debian.ptp_time
      when: not is_ct
    - debian.sudoers
    - { role: "debian.rsyslog", rsyslog_host: "192.168.2.4" }
    - vim.setup
    - ssh.setup
    - role: debian.kerberos
      when: not skip_kerberos
