- name: Builds a machine from a fresh Debian install
  hosts: all

  roles:
    - gai.private
    - debian.nocd
    - apt-cache.proxy
    - debian.base
    - role: debian.notime
      when: (is_ntp is undefined or not is_ntp) and (is_ct is defined and is_ct)
    - role: debian.ptp_time
      when: (is_ntp is undefined or not is_ntp) and (is_ct is undefined or not is_ct)
    - debian.sudoers
    - debian.rsyslog
    - role: debian.ssmtp
      when: is_mail_relay is undefined or not is_mail_relay
    - vim.setup
    - ssh.setup
    - role: debian.kerberos
      when: skip_kerberos is undefined or not skip_kerberos
    - role: debian.nut
      when: needs_ups is defined and needs_ups
