- import_playbook: build-base.yml
  when: sm is not defined or not sm

- name: Set up Proxmox servers
  hosts: proxmox
  roles:
    - role: debian.ntpsec
      hosts: '{{ groups["proxmox"] }}'
    - checkmk.agent

- name: Set up Primary nameserver
  hosts: ns0
  roles:
    - kerberos.master
    - bind.master
    - postgres.master
    - stork.repo
    - stork.agent

- name: Set up Stork server
  hosts: stork
  roles:
    - stork.repo
    - stork.server

- name: Set up Secondary nameserver
  hosts: ns2
  roles:
    - bind.slave
    - stork.repo
    - stork.agent

- name: Set up Auth Services
  hosts: auth
  serial: 1
  roles:
    - postgres.slave
    - postgres.keepalived
    - kerberos.slave

- name: Set up web server
  hosts: web
  roles:
    - apache.server

- name: Set up fax server
  hosts: fax
  roles:
    - hylafax.server

- name: Set up VLAN NTP servers
  hosts: vlan_time
  roles:
    - role: debian.ntpsec
      ntpsec_source: local

- name: Set up SMTP relay
  hosts: smtp
  roles:
    - mail.postfix_relay

- name: Set up Camera DHCP server
  hosts: camera_dhcp
  roles:
    - role: dhcp.server
      dhcp:
        v4Tag: "camera-DHCP4-server"
    - kea.agent
    - stork.repo
    - stork.agent

- name: Set up IoT DHCP server
  hosts: iot_dhcp
  roles:
    - role: dhcp.server
      dhcp:
        v4Tag: "iot-DHCP4-server"
        ddns:
          forwardZones: ["iot.oh.qwop.net"]
          reverseZones: ["254.168.192.in-addr.arpa"]
          dnsServers: ["192.168.2.3"]
          key: "iot-key"
    - kea.agent
    - stork.repo
    - stork.agent

- name: Set up Base DHCP server
  hosts: dhcp
  roles:
    - role: dhcp.server
      dhcp:
        v4Tag: "main-DHCP4-server"
        v6Tag: "main-DHCP6-server"
        ddns:
          forwardZones: ["dhcp.oh.qwop.net"]
          reverseZones: ["2.168.192.in-addr.arpa"]
          dnsServers: ["192.168.2.3"]
          key: "dhcp-key"
    - kea.agent
    - stork.repo
    - stork.agent

- name: Set up GitLab Runner
  hosts: gitlab_runner
  roles:
    - gitlab.runner

- name: Set up CheckMK Server
  hosts: checkmk
  roles:
    - checkmk.server
    - checkmk.agent

- name: Set up BirdNET server
  hosts: birdnet
  roles:
    - birdnet-go.server
