- name: Add Gitlab APT Key
  become: true
  ansible.builtin.get_url:
    url: https://packages.gitlab.com/runner/gitlab-runner/gpgkey
    dest: /etc/apt/keyrings/gitlab-runner.asc

- name: Add Gitlab APT Repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/gitlab-runner.asc] http://HTTPS///packages.gitlab.com/runner/gitlab-runner/debian/ bookworm main"
    state: present
    filename: gitlab-runner

- name: Install GitLab Runner
  become: true
  ansible.builtin.apt:
    pkg:
      - gitlab-runner
      - docker.io
    state: present
    update_cache: true
