- name: Add Gitlab APT Repo
  become: true
  ansible.builtin.deb822_repository:
    uris: http://HTTPS///packages.gitlab.com/runner/gitlab-runner/debian/
    suites: bookworm
    components: main
    signed_by: https://packages.gitlab.com/runner/gitlab-runner/gpgkey
    name: gitlab-runner

- name: Install GitLab Runner
  become: true
  ansible.builtin.apt:
    pkg:
      - gitlab-runner
      - docker.io
    state: present
    update_cache: true
