- name: Restart Kea v4
  become: true
  ansible.builtin.service:
    name: kea-dhcp4-server
    state: restarted

- name: Restart Kea v6
  become: true
  ansible.builtin.service:
    name: kea-dhcp6-server
    state: restarted

- name: Restart Kea DDNS
  become: true
  ansible.builtin.service:
    name: kea-dhcp-ddns-server
    state: restarted
