- name: Install apt-auto-proxy
  become: true
  ansible.builtin.apt:
    deb: https://oh.qwop.net/auto-apt-proxy_14.1_all.deb
    update_cache: false
  when: ansible_distribution == 'Devuan'

- name: Install apt-auto-proxy
  become: true
  ansible.builtin.apt:
    pkg: auto-apt-proxy
  when: ansible_distribution == 'Debian'

- name: Remove deprecated proxy file
  become: true
  ansible.builtin.file:
    path: /etc/apt/apt.conf.d/00aptproxy
    state: absent
