- name: Install apt-auto-proxy
  become: true
  ansible.builtin.apt:
    pkg: auto-apt-proxy

- name: Remove deprecated proxy file
  become: true
  ansible.builtin.file:
    path: /etc/apt/apt.conf.d/00aptproxy
    state: absent
