- name: Install Postgres backup script
  become: true
  ansible.builtin.template:
    src: templates/postgres-backup.sh.j2
    dest: /opt/backup/postgres-backup.sh
    owner: root
    group: backup
    mode: "0750"
  vars:
    directory: /var/lib/postgresql/backup

- name: Build systemd service
  become: true
  ansible.builtin.template:
    src: templates/postgres-backup.service.j2
    dest: /lib/systemd/system/postgres-backup.service
    owner: root
    group: root
    mode: '0644'

- name: Build systemd timer
  become: true
  ansible.builtin.template:
    src: templates/postgres-backup.timer.j2
    dest: /lib/systemd/system/postgres-backup.timer
    owner: root
    group: root
    mode: '0644'

- name: Start backup timer
  become: true
  ansible.builtin.systemd_service:
    name: postgres-backup.timer
    daemon_reload: true
    enabled: true
    state: started
