- name: Install RELP module
  become: true
  ansible.builtin.apt:
    install_recommends: no
    pkg: rsyslog-relp

- name: Create the rsyslog temp directory
  become: true
  ansible.builtin.file:
    path: /rsyslog
    state: directory
    mode: '0750'
    owner: root
    group: root
  notify: "debian.rsyslog : Restart rsyslog"
  when: not is_syslog_host

- name: Install rsyslog.conf
  become: true
  ansible.builtin.template:
    src: "{{ is_syslog_host | ternary('templates/server.rsyslog.conf.j2', 'templates/rsyslog.conf.j2') }}"
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: '0644'
  notify: "debian.rsyslog : Restart rsyslog"
