- name: Install Kea v4
  become: true
  ansible.builtin.apt:
    install_recommends: no
    pkg:
      - kea-dhcp4-server
      - kea-admin
  when: dhcp.v4Tag is defined

- name: Install Kea v6
  become: true
  ansible.builtin.apt:
    install_recommends: no
    pkg:
      - kea-dhcp6-server
      - kea-admin
  when: dhcp.v6Tag is defined

- name: Install Kea DDNS
  become: true
  ansible.builtin.apt:
    install_recommends: no
    pkg:
      - kea-dhcp-ddns-server
  when: dhcp.ddns is defined

- name: Install v4 config file
  become: true
  ansible.builtin.template:
    src: templates/kea-dhcp4.conf.j2
    dest: /etc/kea/kea-dhcp4.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify: "dhcp.server : Restart Kea v4"
  when: dhcp.v4Tag is defined

- name: Install v6 config file
  become: true
  ansible.builtin.template:
    src: templates/kea-dhcp6.conf.j2
    dest: /etc/kea/kea-dhcp6.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify: "dhcp.server : Restart Kea v6"
  when: dhcp.v6Tag is defined

- name: Install DDNS config file
  become: true
  ansible.builtin.template:
    src: templates/kea-dhcp-ddns.conf.j2
    dest: /etc/kea/kea-dhcp-ddns.conf
    owner: root
    group: _kea
    mode: 0640
    backup: true
  notify: "dhcp.server : Restart Kea DDNS"
  when: dhcp.ddns is defined

- name: Install updates initfile
  become: true
  ansible.builtin.template:
    src: templates/init.j2
    dest: /etc/init.d/kea-dhcp4-server
    owner: root
    group: root
    mode: 0755
  notify: "dhcp.server : Restart Kea v4"
  when: dhcp.v4Tag is defined and ansible_distribution == 'Devuan'
