- name: Instal Ceph FUSE package
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - ceph-fuse

- name: Create Ceph config directory
  become: true
  ansible.builtin.file:
    state: directory
    name: /etc/ceph
    mode: "0750"
    owner: root
    group: root

- name: Install Ceph conf file
  become: true
  ansible.builtin.template:
    src: templates/ceph.conf.j2
    dest: /etc/ceph/ceph.conf
    owner: root
    group: root
    mode: "0640"

- name: Install Ceph key file
  become: true
  ansible.builtin.template:
    src: templates/ceph.client.backups.keyring.j2
    dest: /etc/ceph/ceph.client.backups.keyring
    owner: root
    group: root
    mode: "0640"

- name: Create mountpoint directories
  become: true
  ansible.builtin.file:
    state: directory
    mode: "0750"
    owner: root
    group: backup
    name: "/etc/{{ item }}"
  loop: "{{ cephfs_filesystems }}"

- name: Mount the CephFS volume
  become: true
  ansible.posix.mount:
    src: none
    path: "/mnt/{{ item }}"
    opts: "ceph.id=backups,ceph.client_fs={{ item }},_netdev,defaults"
    state: mounted
    fstype: fuse.ceph
  loop: "{{ cephfs_filesystems }}"

- name: Install Ceph backup script
  become: true
  ansible.builtin.template:
    src: templates/cephfs-backup.sh.j2
    dest: /opt/backup/cephfs-backup.sh
    owner: root
    group: backup
    mode: "0750"
