- name: Restart ClamAV Daemon
  become: true
  ansible.builtin.systemd_service:
    state: restarted
    name: clamav-daemon

- name: Restart ClamAV Milter
  become: true
  ansible.builtin.systemd_service:
    state: restarted
    name: clamav-milter

- name: Restart ClamAV FreshClam
  become: true
  ansible.builtin.systemd_service:
    state: restarted
    name: clamav-freshclam
