- name: Install OpenVPN
  become: true
  ansible.builtin.apt:
    install_recommends: no
    pkg:
     - openvpn

- name: Add OpenVPN Config
  become: true
  ansible.builtin.template:
    src: templates/openvpn.conf.j2
    dest: "/etc/openvpn/{{ item.server }}--{{ item.client }}.conf"
    owner: root
    group: root
    mode: 0644
  loop: "{{ infra.openvpn }}"
  when: item.server == ansible_fqdn

- name: Add OpenVPN Key
  become: true
  ansible.builtin.template:
    src: templates/openvpn.key.j2
    dest: "/etc/openvpn/{{ item.server }}--{{ item.client }}.key"
    owner: root
    group: root
    mode: 0600
  loop: "{{ infra.openvpn }}"
  when: item.server == ansible_fqdn

- name: Enable IP forwarding
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Start Tunnel
  become: true
  ansible.builtin.systemd_service:
    name: "openvpn@{{ item.server }}--{{ item.client }}"
    daemon_reload: true
    enabled: true
    state: started
  loop: "{{ infra.openvpn }}"
  when: item.server == ansible_fqdn
