# vim:ft=ansible:
---

- name: Make sure git directory exists
  file: path=~/git state=directory

- name: Pulling debian-bootstrap
  ansible.builtin.git:
    repo: https://github.com/GregJArnold/debian-bootstrap.git
    dest: ~/git/debian-bootstrap
    version: ansible
