- name: Install MariaDB backup script
  become: true
  ansible.builtin.template:
    src: templates/mariadb-backup.sh.j2
    dest: /opt/backup/mariadb-backup.sh
    owner: root
    group: backup
    mode: "0750"
  vars:
    directory: /var/lib/mysql/backup
