- name: Create ollama group
  become: true
  ansible.builtin.group:
    name: ollama
    system: true

- name: Adding user to ollama group
  become: true
  ansible.builtin.user:
    groups:
      - ollama
    append: true
    name: "{{ ansible_user_id }}"

- name: Create ollama user
  become: true
  ansible.builtin.user:
    create_home: false
    group: ollama
    home: /opt/ollama
    name: ollama
    system: true

- name: Create ollama directory
  become: true
  ansible.builtin.file:
    path: /opt/ollama
    state: directory
    owner: ollama
    group: ollama
    mode: 0770

#- name: Download Ollama
#  become: true
#  ansible.builtin.get_url:
#    url: https://ollama.com/download/ollama-linux-amd64.tgz
#    dest: /opt/ollama

#- name: Unpack ollama
#  become: true
#  ansible.builtin.unarchive:
#    src: /opt/ollama/ollama-linux-amd64.tgz
#    dest: /opt/ollama
#    remote_src: true
#    owner: ollama
#    group: ollama

- name: Build ollama systemd file
  become: true
  ansible.builtin.template:
    src: templates/ollama.service.j2
    dest: /lib/systemd/system/ollama.service
    owner: root
    group: root
    mode: 0644

- name: Start ollama
  become: true
  ansible.builtin.systemd_service:
    name: ollama
    daemon_reload: true
    enabled: true
    state: started
