- name: Install BIND
  become: true
  ansible.builtin.apt:
    install_recommends: no
    pkg:
     - bind9-host
     - bind9

- name: Set up zones
  become: true
  ansible.builtin.template:
    src: templates/named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: 0644
  notify: "bind.split_horizon : Restart bind"

- name: Set up options
  become: true
  ansible.builtin.template:
    src: templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: 0644
  notify: "bind.split_horizon : Restart bind"

- name: Set up keys
  become: true
  ansible.builtin.template:
    src: templates/transfer.keys.j2
    dest: /etc/bind/transfer.keys
    owner: root
    group: bind
    mode: 0644
  notify: "bind.split_horizon : Restart bind"

- name: Set up config
  become: true
  ansible.builtin.template:
    src: templates/named.conf.j2
    dest: /etc/bind/named.conf
    owner: root
    group: bind
    mode: 0644
  notify: "bind.split_horizon : Restart bind"
