# vim:ft=ansible:
---

- name: Update all packages to their latest version
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install packages
  become: true
  ansible.builtin.apt:
    install_recommends: no
    pkg:
      - strace
      - tcpdump
      - aptitude
      - git
      - dnsutils
