- name: Install sudo
  become: true
  ansible.builtin.apt:
    pkg: sudo
    install_recommends: false

- name: Make sudoers not prompt for a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo\s+ALL='
    line: '%sudo  ALL=(ALL:ALL) NOPASSWD:ALL'
    validate: /usr/sbin/visudo -cf %s
